version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres15-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
